### PR TITLE
fix(focus-trap): use isTabbable and allow focus to CDK overlays ( #682, #687 )

### LINKED ISSUE #682: Bug: NgpFocusTrap focuses elements with tabindex="-1" inside dialog
### Affected Primitive

NgpDialog

### Version

0.109.4

### Bug Description

`NgpFocusTrap`'s internal `getTabbableCandidates()` function uses `InteractivityChecker.isFocusable()` to determine which elements are tab candidates. It should use `InteractivityChecker.isTabbable()` instead.

`isFocusable()` returns `true` for elements with `tabindex="-1"` (programmatically focusable but **not** reachable via Tab). `isTabbable()` correctly excludes these elements.

**Source:** the `getTabbableCandidates` function inside the focus trap primitive.

```ts
// Current
function getTabbableCandidates(container) {
    const nodes = [];
    const walker = document.createTreeWalker(container, NodeFilter.SHOW_ELEMENT, {
        acceptNode: (node) => interactivityChecker.isFocusable(node)  // ← should be isTabbable
            ? NodeFilter.FILTER_ACCEPT
            : NodeFilter.FILTER_SKIP,
    });
    while (walker.nextNode()) {
        nodes.push(walker.currentNode);
    }
    return nodes;
}
```

## Impact

Using the reproduction example below, the dialog contains: `div[tabindex="-1"]`, `<input>`, Cancel `<button>`, Confirm `<button>`.

1. **Initial focus (`focusFirst`)** — On dialog open, the `div[tabindex="-1"]` receives focus instead of the `<input>`. The focus trap walks the DOM and programmatically focuses the first `isFocusable` candidate, which is the div.

2. **Tab wrapping (`getTabbableEdges`)** — The focus trap calculates `first = div[tabindex="-1"]` and `last = Confirm button`. When the user presses Tab on the Confirm button, focus wraps to the `div[tabindex="-1"]` instead of the `<input>`.

3. **Tab cycling** — This creates a broken cycle: `div[tabindex="-1"] → input → Cancel → Confirm → div[tabindex="-1"] → input → ...` instead of the expected `input → Cancel → Confirm → input → ...`.

## Minimal Reproduction

```html
<button [ngpDialogTrigger]="dialog" ngpButton>Launch Dialog</button>

<ng-template #dialog let-close="close">
  <div ngpDialogOverlay>
    <div ngpDialog>
      <h1 ngpDialogTitle>Publish this article?</h1>

      <div class="dialog-footer">
        <div tabindex="-1">This div should NOT receive focus</div>
        <input placeholder="This input should receive initial focus" />
        <button (click)="close()" ngpButton>Cancel</button>
        <button (click)="close()" ngpButton>Confirm</button>
      </div>
    </div>
  </div>
</ng-template>
```

**Expected:** When the dialog opens, the `<input>` receives initial focus (first tabbable element). Tab cycles between `input → Cancel → Confirm → input`.

**Actual:** The `div[tabindex="-1"]` receives initial focus. Tab wrapping includes the div, creating a broken cycle.

### Steps to Reproduce

_No response_

### Reproduction

https://stackblitz.com/edit/fp3y8gqv-yxdn5pdi?file=src%2Fmain.ts

### PR DESCRIPTION
**Pull request by gourlaouenp**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ng-primitives/ng-primitives/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

- #682: isFocusable() used instead of isTabbable(), causing wrong elements to receive focus                                                                                                                         
- #687: focus incorrectly redirected away from CDK overlays                                                                                                                                                         
                                                                                                                                                                                                                      
No new features, no API changes, just correcting existing behavior. 

<!-- Please check the one that applies to this PR using "x". -->

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

<!-- Please describe the current behavior that you are modifying, or link to a relevant issue. -->

## Issue

Closes #682 #687

## What does this PR implement/fix?

**#682** - **Focus** **trap** **incorrectly** **focuses** **tabindex="-1" elements:**

getTabbableCandidates() used InteractivityChecker.isFocusable() which includes elements with tabindex="-1". Switched to isTabbable() so only keyboard-reachable elements are part of the tab cycle. This fixes incorrect initial focus and broken tab wrapping in dialogs.

**#687** - **Focus** **trap** **blocks** **focus** **to** **CDK** **overlay** **panes:**

When a CDK overlay (e.g. select dropdown) opens from within a focus-trapped container, the overlay renders in .cdk-overlay-container at the document root — outside the trap's DOM. The trap's handleFocusIn and handleFocusOut would forcibly redirect focus back. Added checks to allow focus to move to elements inside another [data-focus-trap] or .cdk-overlay-container without interference.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No



<!-- This is an auto-generated comment: release notes by coderabbit.ai -->
## Summary by CodeRabbit

* **Bug Fixes**
  * Focus-trap now ignores focus moves into other traps or overlay containers, preventing unwanted redirection.
  * Tabbable detection refined to exclude elements with negative tabindex, improving keyboard navigation.

* **Tests**
  * Expanded coverage for tabbable filtering and focus interactions involving overlay containers and separate focus traps.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

### CODE REVIEW

File: packages/ng-primitives/focus-trap/src/focus-trap/focus-trap-state.ts [hunk 1]
```diff
@@ -205,7 +210,11 @@ export const [NgpFocusTrapStateToken, ngpFocusTrap, injectFocusTrapState, provid
 
         const relatedTarget = event.relatedTarget as HTMLElement;
 
-        if (!element.nativeElement.contains(relatedTarget)) {
+        if (
```
Comment (ashley-hunter) [inline packages/ng-primitives/focus-trap/src/focus-trap/focus-trap-state.ts:210]: Could we add a comment here explaining the reason we need to do this? Perhaps with a link to the issue in question so we can refer back to later.

Comment (gourlaouenp) [reply packages/ng-primitives/focus-trap/src/focus-trap/focus-trap-state.ts:210]: Done
