### PR TITLE
fix(form-control): apply native disabled attribute to ngpFormControl host element

### LINKED ISSUE #362: ngpFormControl disabling not working
### Affected Primitive

Form-Field

### Version

0.63.0

### Bug Description

The ngpFormControl directive does not properly apply the disabled state to the underlying form control element. Despite setting the ngpFormControlDisabled input or the control being marked as disabled via parent state, the native disabled attribute is not reflected on the element, resulting in a control that appears enabled and is still focusable/interactable.

### Steps to Reproduce

1.	Use <input ngpFormControl [ngpFormControlDisabled]="true" /> in a template.
2.	Observe that the input is still interactive and does not have the native disabled behavior.	

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by kostetskyroma**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ng-primitives/ng-primitives/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## Issue

Closes #362 

## What does this PR implement/fix?

This PR fixes an issue where the ngpFormControl directive was not properly disabling native form elements.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/ng-primitives/form-field/src/form-control/form-control.ts [hunk 1]
```diff
@@ -22,6 +22,9 @@ import { formControlState, provideFormControlState } from './form-control-state'
   selector: '[ngpFormControl]',
   exportAs: 'ngpFormControl',
   providers: [provideFormControlState()],
+  host: {
+    '[attr.disabled]': 'status().disabled ? "" : null',
+  },
```
Comment (ashley-hunter) [inline packages/ng-primitives/form-field/src/form-control/form-control.ts]: I think we need to make one additional check here, the disabled input is only valid on certain HTML elements, we should check to make sure we only apply it where valid.

**Review by ashley-hunter — CHANGES_REQUESTED** [review]
Thank you very much for the contribution! Looks good, just noticed one additional check we should make

File: packages/ng-primitives/form-field/src/form-control/form-control.ts (hunk 1 above)
Comment (kostetskyroma) [reply packages/ng-primitives/form-field/src/form-control/form-control.ts]: This makes me consider changing the selector property to apply ngpFormControl only where it is allowed:

```
selector: 'input[ngpFormControl], select[ngpFormControl], textarea[ngpFormControl], button[ngpFormControl], optgroup[ngpFormControl], option[ngpFormControl]',
```

This way, we filter out all ineligible uses of the ngpFormControl directive upfront. As a result, we no longer need to manually check properties like disabled within the directive.

Additionally, if we introduce similar properties in the future, we can avoid adding separate checks for each one.

@ashley-hunter what do you think about it?

Comment (ashley-hunter) [reply packages/ng-primitives/form-field/src/form-control/form-control.ts]: Thanks! The primary function of the directive is to apply data attributes representing the state to an attribute, and this may or may not be related to an underlying html element or not, so I don't think we want to limit it to just those. For example, in Angular material the form classes and aria attributes get applied to a mat-select element:

image

I think the most flexible way would be to inject the `HOST_TAG_NAME` and use it to detect whether the element supports the attribute and conditionally apply it.

Comment (kostetskyroma) [reply packages/ng-primitives/form-field/src/form-control/form-control.ts]: @ashley-hunter Thanks for the feedback! Could you check this commit [refactor(form-control): enhance disabled attribute handling for ngpFo…](https://github.com/ng-primitives/ng-primitives/pull/363/commits/e31ec53c06f36583bd589a9fd61b52e683e849be)? Is this what you expected?

**Review by ashley-hunter — APPROVED** [review]
Great! Thank you!
