### PR TITLE
fix/feat(progress): correct reference between ngpProgress and ngpProgressLabel

### LINKED ISSUE #536: NgpProgressLabel does not assign ID attribute to host
### Affected Primitive

Progress

### Version

0.90.0

### Bug Description

When applying the `ngpProgressLabel` directive to a label, an ID is internally generated, but not assigned to the host component the directive is applied to.

As a result, the component that has the `NgpProgress` directive points to this ID with the `aria-labelledby` attribute, but no node with this ID exists.

### Steps to Reproduce

Example:
```html
<div ngpProgress [ngpProgressValue]="50">
  <span ngpProgressLabel></span>
  <span ngpProgressValue></span>

  <div ngpProgressTrack>
    <div ngpProgressIndicator></div>
  </div>
</div>
```

Resulting HTML:

Image

##### Expected behaviour

The `<span>` with the `ngpProgressLabel` directive has the ID `ngp-progress-label-0`.

##### Actual behaviour

The `<span>` has no ID attribute.

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by janek64**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ng-primitives/ng-primitives/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## Issue

Closes #536 

## What does this PR implement/fix?

**Summary:** Implements correct referencing between the `ngpProgress` and `ngpProgressLabel` via HTML attributes that was previously missing.

* Sets the `id` attribute for the host of `ngpProgressLabel` and fixes the `aria-labelledby` attribute in `ngpProgress` to correctly reference it.
* Sets `id` attribute for the host of `ngpProgress` and references it via the `for` attribute of the host of `ngpProgressLabel`.
* Updates the documentation and reusable component to use `<label>` instead of `<span>` for the label so that the `for` attribute can be correctly applied.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

(The reusable component for _Progress_  now uses `<label>` instead of `<span>` - I am not sure if this is considered a breaking change).

### CODE REVIEW

File: packages/ng-primitives/progress/src/progress-label/progress-label.ts [hunk 1]
```diff
@@ -6,6 +6,8 @@ import { injectProgressState } from '../progress/progress-state';
   selector: '[ngpProgressLabel]',
   exportAs: 'ngpProgressLabel',
   host: {
+    '[attr.id]': 'id()',
+    '[attr.for]': 'state().id()',
```
Comment (ashley-hunter) [inline packages/ng-primitives/progress/src/progress-label/progress-label.ts]: Could we possibly add a check here to see if the element is a label element and only add the for attribute when it is? The selector technically allows any element, and people may be using other elements and the for attribute is only valid on labels.

**Review by ashley-hunter — APPROVED** [review]
Great work! Thank you very much!

**Comment by ashley-hunter** [comment]
@allcontributors add @janek64 for code.
